feat: Adicionando teste do banco na pipeline

diff --git a/.github/workflows/k8s-deploy.yml b/.github/workflows/k8s-deploy.yml
--- a/.github/workflows/k8s-deploy.yml
+++ b/.github/workflows/k8s-deploy.yml
@@ -101,10 +101,12 @@ jobs:
               run: kubectl apply -f k8s/hpa.yaml
 
             - name: Test database connection
+              continue-on-error: true
               run: |
                   kubectl apply -f k8s/db-test.yaml
-                  kubectl wait --for=condition=Ready pod/db-test-8 --timeout=60s || true
-                  kubectl logs db-test-8
+                  kubectl wait --for=jsonpath='{.status.phase}'=Succeeded pod/db-test-8 --timeout=60s || \
+                  kubectl wait --for=jsonpath='{.status.phase}'=Failed pod/db-test-8 --timeout=5s || true
+                  kubectl logs db-test-8 || echo "Could not retrieve logs"
                   kubectl delete pod db-test-8 --ignore-not-found=true
 
             - name: Wait rollout
